### ISSUE TITLE
Pre-launch checklist

### ISSUE THREAD

**Issue by blutz** [blutz/ninteen-thirty-four#6]
- [x] Google Analytics
- [x] HTTPS
- [x] Migrate database URLs to unicamp.org
- [x] archive.unicamp.org (w/ password)
- [x] kill dev (since they'll now share a db)

**Comment by blutz** [comment]
Launched!
